name: Build and Deploy to Appetize.io

on:
  # 1. Run when code is merged into the main branch
  push:
    branches: [ main ]

  # 2. ALSO run when a Pull Request is opened/updated that targets the main branch
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build Next.js static site
      run: npm run build

    - name: Sync Capacitor project
      run: cd tutorial-task-android-app && npx cap sync android

    - name: Build Android APK
      run: cd android && ./gradlew assembleDebug

    - name: Upload to Appetize.io and Create Test Link
      run: |
        APK_PATH="android/app/build/outputs/apk/debug/app-debug.apk"
        API_TOKEN="${{ secrets.APPETIZE_API_TOKEN }}"
        
        RESPONSE=$(curl "https://api.appetize.io/v1/apps" -F "file=@$APK_PATH" -F "platform=android" -u "$API_TOKEN: ")
        
        APP_URL=$(echo $RESPONSE | jq -r .appURL)
        
        echo "Your app is ready to test at: $APP_URL"
        echo "Test Link: $APP_URL" >> $GITHUB_STEP_SUMMARY
